mod cons;
mod dna;
mod fib;
mod fibd;
mod gc;
mod grph;
mod hamm;
mod iev;
mod iprb;
mod lcsm;
mod orf;
mod prob;
mod prot;
mod prtm;
mod revc;
mod rna;
mod subs;

#[allow(dead_code)]
fn main() {
    // println!("DNA:");
    // dna::count("data/rosalind_dna.txt");
    // println!("\nRNA:");
    // rna::transcribe("data/rosalind_rna.txt");
    // println!("\nREVC:");
    // revc::complement("data/rosalind_revc.txt");
    // println!("\nFIB:");
    // fib::run("data/rosalind_fib.txt");
    // println!("\nHAMM:");
    // hamm::run("data/rosalind_hamm.txt");
    // println!("\nPROT:");
    // prot::run("data/rosalind_prot.txt");
    // println!("\nFIBD:");
    // fibd::run("data/rosalind_fibd.txt");
    // println!("\nGC:");
    // gc::run("data/rosalind_gc.txt");
    // println!("\nIPRB:");
    // iprb::run("data/rosalind_iprb.txt");
    // println!("\nSUBS:");
    // subs::run("data/rosalind_subs.txt");
    // println!("\nCONS:");
    // cons::run("data/rosalind_cons.txt");
    // println!("\nGRPH:");
    // grph::run("data/rosalind_grph.txt");
    // println!("\nIEV:");
    // iev::run("data/rosalind_iev.txt");
    // println!("\nLCSM:");
    // lcsm::run("data/rosalind_lcsm.txt");
    // println!("\nORF:");
    // orf::run("data/rosalind_orf.txt");
    // println!("\nPRTM:");
    // prtm::run("data/rosalind_prtm.txt");
    println!("\nPROB:");
    prob::run("data/rosalind_prob.txt");
}
